### ISSUE TITLE
reporting issue

### ISSUE THREAD

**Issue by nachotacos69** [HaoJun0823/GECV#1]
i'll update my issues later

**Comment by nachotacos69** [comment]
ISSUES

![BIN Version of TR2 Editor](https://github.com/HaoJun0823/GECV/assets/99103531/f1a085d9-6468-4676-8fc5-01b0e5aa3d09)
![GERDP](https://github.com/HaoJun0823/GECV/assets/99103531/bdf03289-172e-4753-a931-c110d9ce5664)
![RETAEDOG](https://github.com/HaoJun0823/GECV/assets/99103531/153085a1-96a7-4548-a784-bc8fd1eeebb5)

**Comment by HaoJun0823** [comment]
The TR2 Bin version tool has been deprecated because the TR2 GUI has been fully parsed, and the Bin version is only for program analysis.

GERDP is a Chinese program used to process PSV and PS4 version game images, and this is a Chinese program, you need to call the home directory of these game images as a parameter.

RETAEDOG needs to work with a retaedog asset, and since we cannot upload game data, there will be no instructions for this tool at the moment.

Please note again that the main maintainers are still working on it and there will not be any workflow instructions for these tools at this time.

**Comment by nachotacos69** [comment]
Understood :)

But currently everything works well especially for the tr2 gui, it works on previous versions for GOD/GODS EATER BURST and GOD EATER 2 (PSP)

**Comment by nachotacos69** [comment]
Also do you guys have a group chat or something, I'm not really good accessing on Chinese related stuff, sorry

**Comment by HaoJun0823** [comment]
There is currently no live chat group for the international community, and although there is a Telegram, no one talks.

Moreover, all tools are developed for the PC versions of GE2RB and GER. On earlier game platforms, the formats of TR2, GNF and other files are completely different. There will not be any updates in this part because large-scale modifications to console games are not Our main mission.

**Comment by nachotacos69** [comment]
understood :)

**Comment by nachotacos69** [comment]
i'll be closing this issue now, i think i get along with the stuff... also i could say everything works as my feedback, i hope another update would be released that fixes the second option in the tool (the PRES method), it uses a lot of memory which can be a problem which results into a restart of the computer automatically.. but overall everything works
