### ISSUE TITLE
i need help on how blz2 extraction works

### ISSUE THREAD

**Issue by DarkGD123** [HaoJun0823/GECV#11]
Just finished reading @nachotacos69 [WikiEater related to GE2 1.40 DLC (DECRYPTED](https://github.com/nachotacos69/WikiEater/blob/main/GOD%20EATER%202/GOD%20EATER%202%20DLC%20(1.40%20DECRYPTED).md)

i tried copying the blz2 part on the dlc even though there is alot
![Screenshot (148)](https://github.com/HaoJun0823/GECV/assets/42462384/e43a8d13-fa4e-46f6-859d-a4ec7ee4caa3)

then pasted them in a new file then i had this issue when i use the tool
```
> GECV_EX_BLZ4.exe unpack "blz2_1.blz2" "blz2_1.blz2.new" blz2
GECV EX BLZ BY RANDERION(HAOJUN0823)
https://blog.haojun0823.xyz/
https://github.com/HaoJun0823/GECV
Unhandled exception. ComponentAce.Compression.Libs.zlib.ZStreamException: inflating: unknown compression method
   at ComponentAce.Compression.Libs.zlib.ZOutputStream.Write(Byte[] b1, Int32 off, Int32 len)
   at GECV_EX.Utils.BLZ4Utils.CopyStream(Stream input, Stream output) in F:\Documents\VS2022\GECV\GECV II\GECV_EX\Utils\BLZ4Utils.cs:line 105
   at GECV_EX.Utils.BLZ4Utils.DecompressData(Byte[] inData, Byte[]& outData) in F:\Documents\VS2022\GECV\GECV II\GECV_EX\Utils\BLZ4Utils.cs:line 91
   at GECV_EX.Utils.BLZ2Utils.BLZ2FileDecompresser.GetByteResult() in F:\Documents\VS2022\GECV\GECV II\GECV_EX\Utils\BLZ2Utils.cs:line 237
   at GECV_EX.Utils.BLZ2Utils.UnpackBLZ2Data(Byte[] blz2_file) in F:\Documents\VS2022\GECV\GECV II\GECV_EX\Utils\BLZ2Utils.cs:line 49
   at GECV_EX_BLZ4.Program.Unpack2(String blz, String file) in F:\Documents\VS2022\GECV\GECV_EX_BLZ4\Program.cs:line 116
   at GECV_EX_BLZ4.Program.Main(String[] args) in F:\Documents\VS2022\GECV\GECV_EX_BLZ4\Program.cs:line 32
```

**Comment by nachotacos69** [comment]
im not sure thats how it works, like the copy pasting part 🤔

**Comment by nachotacos69** [comment]
[PATCH.indx.txt](https://github.com/HaoJun0823/GECV/files/15059163/PATCH.indx.txt)

i made a little list where to find blz2 only read the **START** part.. and ***avoid checking the END, since i made it for other purposes***

**Comment by nachotacos69** [comment]
@HaoJun0823 I'll do the testing, I'll try to report after I fix some internet issues lol

**Comment by HaoJun0823** [comment]
> [PATCH.indx.txt](https://github.com/HaoJun0823/GECV/files/15059163/PATCH.indx.txt)
> 
> i made a little list where to find blz2 only read the **START** part.. and _**avoid checking the END, since i made it for other purposes**_

Both BLZ4 and BLZ2 are compressed through a series of zlib methods.

BLZ4 decompresses/compresses the data stream through ZLIB, while BLZ2 uses DEFLATED.

The header of BLZ4 is four-byte BLZ4:
The decompressed size of four bytes (actually eight bytes, but the game does not have a single file larger than Int32, and this part of the design is also used in the file sections of PS4 and PSV).
Eight bytes of 0, (see above, it should be four bytes of 0)
Sixteen-byte MD5,
So the header file has a fixed size of 32 bytes.

The BLZ2 header is four bytes of BLZ2 with no additional verification data.

Next, it consists of multiple blocks, each block has a 2-byte block size (UINT16) and block data.
Read the block size in sequence, and then read the block data according to the block size until the end of the file.

Since BLZ uses 16-byte alignment in some places (such as RDP), it should end when reading a block size of 00.

Then, the game uses a strange order to store these chunks, for example the order of 0,1,2,3,4, in BLZ the order is 1,2,3,4,0, so you need to reverse it and pass it through zlib in order Stream decompression/compression.

For BLZ2, when the file is less than or equal to 0XFF, no compression is performed, so there is only one block.

For BLZ4, some files are not compressed, but these files may have multiple uncompressed chunks.

Some of the original data blocks will become larger through the zlib compressed stream, so my blz4 strategy sets each block size to 32768, while blz2 keeps the size of 0xff online.

**Comment by HaoJun0823** [comment]
I think my V4 version completely solves the problem of compressing/decompressing BLZ2 files.
BLZ2's data blocks have special compression format settings that I can't adjust through Microsoft's libraries so I can only decompress them.
So I didn't find a library in .NET to process files. I wrote a python version based on the py file that someone gave me before.

**Comment by nachotacos69** [comment]
Using GOD EATER 2 1.40 DLC, i use my self made tool just to just rip some blz2 stuff inside the `PATCH.EDAT` file

Before
![Screenshot (152)](https://github.com/HaoJun0823/GECV/assets/99103531/f39f01a8-0fba-4ea2-b216-65d1b40f935b)

After
![Screenshot (153)](https://github.com/HaoJun0823/GECV/assets/99103531/19eb11ff-d187-48e1-b8f1-15d4e74463fd)

**Comment by DarkGD123** [comment]
Closing this one..

Yamato should send something later on @HaoJun0823
