### ISSUE TITLE
Info:TR2 Editor

### ISSUE THREAD

**Issue by HaoJun0823** [HaoJun0823/GECV#18]
So with the help of @qingyu510 I added support for editing old version tr2 files.
Please open/save the old(some old game) format through the secondary menu of the "old tr2" menu.

![image](https://github.com/HaoJun0823/GECV/assets/26188180/ca8de709-38d1-4a65-9425-42c740264dc4)

After the program is tested correctly, I will close this issue and merge it into the release.

**Comment by nachotacos69** [comment]
Using: GOD EATER 2 (version 1.40 since i don't have the base game)

$\color{#9966ff}{\textsf{==ISO SECTION==}}$
Image 1: using common_text in system.res
Condition/Result: $\color{#40ff00}{\textsf{Okay}}$  
![Screenshot (173)](https://github.com/HaoJun0823/GECV/assets/99103531/ee464dda-3f94-4782-a2da-b6ff6011e343)
Image 2: using network_text in system.res
Condition/Result: $\color{#40ff00}{\textsf{Okay}}$ 
![Screenshot (175)](https://github.com/HaoJun0823/GECV/assets/99103531/b0738d04-0049-4ba0-b0ff-659a550711cf)

$\color{#4d88ff}{\textsf{==DLC SECTION==}}$
Image 1: using common_text in system_update.edat
Condition/Result: $\color{#40ff00}{\textsf{Okay}}$ 
![Screenshot (178)](https://github.com/HaoJun0823/GECV/assets/99103531/99f4cd5c-131b-4f3a-b6ca-9487baefda0c)
Image 2: using network_text in system_update.edat
Condition/Result: $\color{#ff1a1a}{\textsf{Error}}$
Reason: Only error occurred when using the OLD TR2, using regular works okay
![Screenshot (179)](https://github.com/HaoJun0823/GECV/assets/99103531/b32e8b97-d4bb-46a1-a8bb-2140d15dbb92)

here's the files just for you to mess around or do whatever you need:
[system and system update.zip](https://github.com/HaoJun0823/GECV/files/15211480/system.and.system.update.zip)

do note that my extraction on blz2 is really stiff so i suggest you do the honors to extract blz2 + i currently have no plans to create a full fledge to extract GE2 contents

**Comment by nachotacos69** [comment]
GOD EATER BURST (With 1.01 Patch/Update `because of 1.61 dlc i had to forcefully update the iso`)
Note: GOD EATER BURST does not use BLZ2, so the way the extraction/repack works is related to `Pres` (based on: https://github.com/gil-unx/GEBCS source code)

$\color{#e6e600}{\textsf{==ISO SECTION==}}$
Some $\color{#ff3333}{\textsf{Bad}}$ and some $\color{#66ff1a}{\textsf{Good}}$, but some files can and can't be viewed in OLD TR2 and sometimes deemed as duplicates if you know what i mean. It gets triggered usually long tr2 indexes/columns especially for `mission.tr2` and `article.tr2`, im just gonna mention some small stuff that is now editable before the public test

Section 1: base_text.tr2
Condition: $\color{#66ff1a}{\textsf{Good}}$
![Screenshot (180)](https://github.com/HaoJun0823/GECV/assets/99103531/450311e7-128e-4273-b56c-a255a037c94c)
-  $\color{#0080ff}{\textsf{Mission Rank}}$
![NPJH50352_00001](https://github.com/HaoJun0823/GECV/assets/99103531/f800ffd5-9681-42cc-bf29-71e7be5b7efc)
- $\color{#ff0080}{\textsf{Terminal}}$
![NPJH50352_00002](https://github.com/HaoJun0823/GECV/assets/99103531/72dc786e-c7d1-4be4-93f0-e40f5953e98d)


Section 2: game_text.tr2
Condition: $\color{#66ff1a}{\textsf{Good}}$
![Screenshot (181)](https://github.com/HaoJun0823/GECV/assets/99103531/3e701c70-bde4-4ce1-b426-09d573063dfe)

- $\color{#1ab2ff}{\textsf{Start Button Menu}}$
![NPJH50352_00003](https://github.com/HaoJun0823/GECV/assets/99103531/c702e279-0a65-4180-ba5e-b1d2bfc7962c)


$\color{#ff6600}{\textsf{==DLC SECTION==}}$
Note: using [GEBUtils](https://github.com/nyirsh/GEBUtils), i manage to extract .tr2 files.. but sadly, repacking the tr2 files back to dlc, corrupts the dlc even modifying a few texts here and there + it freezes the PSP too

Others: Missing Texts on OLD TR2
Take en_base as an example. The japanese and regular texts go missing, then some values go NULL when using OLD TR2, but using a regular one makes it visible again

- $\color{#ff4d4d}{\textsf{Nulls and Missing Texts}}$
![Screenshot (182)](https://github.com/HaoJun0823/GECV/assets/99103531/cb797df5-d95c-4bf3-a911-581c3b1ec229)
- $\color{#88ff4d}{\textsf{Normal}}$
![Screenshot (183)](https://github.com/HaoJun0823/GECV/assets/99103531/248f4467-8fd0-407f-8564-de0bd64e4074)


Let me know if i said something incorrect

**Comment by HaoJun0823** [comment]
Please package the tr2 of these errors into a zip and I will analyze it further.

In fact, the version of the tr2 file does not necessarily depend on the game version. Since there is no obvious mark, I dare not write my own method to determine the header file to select the loader version.

The obvious differences we know so far: the old tr2 does not have an id set at the beginning, and the new one has:

This is a new version of tr2. Usually there is an id sequence before the next bin data.
![image](https://github.com/HaoJun0823/GECV/assets/26188180/652bf1bd-85ea-4220-96d5-f208004f38cc)

The old file doesn't have this.
I suggest you further determine what versions these files are and then choose how to load them.

**Comment by nachotacos69** [comment]
all right then, i'll dig deeper on this one

**Comment by HaoJun0823** [comment]
> all right then, i'll dig deeper on this one

I asked qingyu and he tested it and there was no problem:
On consoles, there is a mix of newer versions (PC) and older versions (which I labeled SONY_A).
So... you can judge these files the way I teach you.

"geb starts en_xxxxx series of data are all new tr2"
That's what he said.

**Comment by nachotacos69** [comment]
currently my tools that I use for GEB is: https://github.com/gil-unx/GEBCS

as for GE2.. nothing really.. so I mostly just gather/copy any possible blz2 data and hope that it's gonna be a .tr2 💀 because I mostly get gmo and gim (model and texture)

**Comment by DarkGD123** [comment]
> currently my tools that I use for GEB is: https://github.com/gil-unx/GEBCS
> 
> as for GE2.. nothing really.. so I mostly just gather/copy any possible blz2 data and hope that it's gonna be a .tr2 💀 because I mostly get gmo and gim (model and texture)


 try to use chatgpt or something else

**Comment by nachotacos69** [comment]
>the try to use chatgpt or something else

NO.

**Comment by HaoJun0823** [comment]
> Ahh I see, i'll see what I can do tomorrow, since I just turned off my pc

I released the release version.
The current version can automatically determine what version tr2 is.

Everything tested so far is normal.
The tr2 editor has an export text function, which can export each text into a separate bin without damaging the encoding.
At present, translators have a headache and do not have a useful tool to coordinate these files.
I hope to find out in the future that humans should have such a software to modify txt in batches, right...

**Comment by nachotacos69** [comment]
Gonna check the update tomorrow, I'm glad I could help on this one

Did I though?
