### ISSUE TITLE
TR2 Editor: Test feedback on new Excel import and export functions

### ISSUE THREAD

**Issue by HaoJun0823** [HaoJun0823/GECV#19]
Because @qingyu510 told me that he has trouble translating a large amount of content. There are hundreds of thousands of files scattered in various places and cannot be compared.

The reason why this function is disabled is due to UTF-16. Since the game may have special characters, data may be lost during automatic conversion due to program errors. Therefore, when you double-click a text cell in the editor, the text editor will pop up. This editor ensures that the encoding is correct.

Therefore, the editor actually has two tables. The first one displays the data correctly, and the second one stores the hexadecimal value of the data. These two tables work together to achieve all this. This is why the old program The reason for exporting two tables.

So, for the convenience of anyone, I rewrote the excel part and implemented myself encoding unified text into UTF-16, which allowed excel to read everything correctly.

After you export, you will find an "import" column behind it.
There are three values here:
0=Do not import.
1=Import value column.
2=Import hex column. (Only text supports this type)

You just need to choose which way to import, so you don't need to modify both, only the parts you need.

Note that this import may still have errors, but this is expected since Excel is not under my control and you need to back up your data.
You need to carefully proofread whether the content is correct and manually correct incorrect ones in the editor.

If this thing doesn't work well, Export txt, Import txt will be more stable.

I posted this issue to get feedback. Does this feature work properly?

**Comment by HaoJun0823** [comment]
Please help me check a character in a text, its hexadecimal is: 17 FF
Please help me check whether this character is normal in Excel.

**Comment by HaoJun0823** [comment]
It is normal if wrong characters are displayed in excel.
Because the game has some custom characters that use blank parts of the encoding set.

I recommend using HEX to modify this part, or modifying it visually in the editor.

**Comment by nachotacos69** [comment]
just woke up, might try this later on GEB or whatever game currently i want to do with it

**Comment by nachotacos69** [comment]
_`I used GEB today for now, I currently don't have the PC game since i uninstalled them + I'm defragging my hard drive at the moment`_

File i modified (with the semi translation here as the example from this post): 
[god_m003_Gift.zip](https://github.com/HaoJun0823/GECV/files/15215220/god_m003_Gift.zip)
Log File: [text.tr2.log](https://github.com/HaoJun0823/GECV/files/15215240/text.tr2.log)


$\color{#99e600}{\textsf{Feedback:}}$ 
Overall, I mostly rely on my translation by converting regular text into a compatible UTF-16LE Hex conversion which i got from here: https://dencode.com/en/string/hex
- I only modified the HEX values since it uses UTF-16LE after all and set all the Import Values to 2
![Screenshot (190)](https://github.com/HaoJun0823/GECV/assets/99103531/5973ff6b-63cd-4bdb-87e1-8b1ac25239c1)
- After using "Import Excel" it worked nicely
![Screenshot (189)](https://github.com/HaoJun0823/GECV/assets/99103531/c779e292-f7e0-4560-992f-b3a81a4e02de)

$\color{#b366ff}{\textsf{Before and After:}}$ (Repacked using [GEBCS](https://github.com/gil-unx/GEBCS/) since that's the only tool capable repacking GEB and Screenshot using TempAR PSP Plugin)
![image](https://github.com/HaoJun0823/GECV/assets/99103531/8d84303d-c511-4422-a9b5-080b5e394fc2)
![image](https://github.com/HaoJun0823/GECV/assets/99103531/7973dcea-246f-40e9-883a-3ee92c4ed3c6)
