### ISSUE TITLE
Request for a Old Game Support

### ISSUE THREAD

**Issue by DarkGD123** [HaoJun0823/GECV#4]
Hello @HaoJun0823, Can you add a support for **GOD EATER BURST** and **GOD EATER 2**

considering there is no modding/tool for those games, I really would appreciate if there are tools for this older games

**Comment by nachotacos69** [comment]
I have some suggestions for you my guy.. since im atleast the only active person here because I use the tool for some days now and I will give you some alternatives

# [GOD EATER PSP TOOLS]



1. [GEBCS](https://github.com/gil-unx/GEBCS) by gilunx

**Good Things**
- Supports only GOD EATER BURST (USA, JP, EUR)
- Can extract all of the contents within package.rdp of GOD EATER BURST
- Can modify some parts here and there (slightly).

**Bad Things**
- Slight modification can lead to some issues, although modifying the text indexes doesn't lead to bad things.
- Mostly changing models whatsoever is very incompatible
- Adding some extra things makes the tool crash.
- Supports the very first version of GOD EATER but it gets corrupted with a couple of text modification




2. [GEBUtils](https://github.com/nyirsh/GEBUtils) by nyirsh

**Good Things**
- Supports only GOD EATER BURST (USA, JP, EUR)
- supports DLC 1.0 to 1.61
- can extract slightly on package.rdp and the dlc contents

**Bad Things**
- Limits your modification by notifying you if a specific file is big or a few bytes free during repacking.
- dlc modification corrupts pretty easily.




3. [GE2 Script](https://github.com/Saramagrean/GE2-insert-script-tool) by Saramagrean

**Good Things**
- Only supports 1.30 iso version
- Supports 1.30 DLC
- Can extract and modify text indexes

**Bad Things**
- incompatible to other version since it's for 1.30
- It only does text modification, and it won't let you modify the texts for combat radio texts.
- lacks full modification of package.rdp/data.rdp.
- DLC have rare chances to be inflate into 1+ GB for no reason, it's the scripts fault commonly



4. [GOD EATER 2 BMS Script] from QuickBMS

**Good Things**
- Supports GE2RB since it's made truly for the vita version
- Supports ISO 1.0 to 1.40
- Nothing Much but can extract a few contents of package.rdp / data.rdp

**Bad Things**
- No DLC Support/Modification
- Most file are corrupted and rather in a broken state
- Unorganized file positions
- Overall, bad experience from using it

Note: 

~ Yamato Nagasaki

**Comment by nachotacos69** [comment]
exactly, might as well close this issue
