### ISSUE TITLE
small questions i guess

### ISSUE THREAD

**Issue by DarkGD123** [HaoJun0823/GECV#6]
Hello, i would like to make some questions here and there and i hope you can answer them

1. is it possible to modify a mission with this tool? (example: removing/adding enemies, modifying values here and there)
2. considering there are files that are missing (like .ixo for a few aragamis) will the tool be fixed?
3. any tools to view models of aragamis, npc, and etc.?
4. any ways to modify audios?

**Comment by nachotacos69** [comment]
I could answer this I guess since @HaoJun0823 is busy let's just say it like that

1. kind of and kind of not, if you have the brains to do so
2. It's probably your issue on incomplete of extracting the files
3. There's a tool called `GERExporter` that apparently views npc models..
4. I use **vgmstream**, it's complicated but yes it's possible to modify audios

**Comment by HaoJun0823** [comment]
1. Yes and no, the existence of the tool only means that it can modify a large number of files. It does not mean that this thing can replace all modification processes. Some content still requires a binary editor because the data is unique.
1.1 This is not a Mod SDK. This set of tools is only developed according to our needs when translating the game.
2. Refer to 1, ixo is not in our parsing plan, and we will not parse content that is not necessary.
2.1 If you want to make up for the missing ixo, the pres packaging tool can add new files.
3. See nachotacos69’s answer.
4. Bandai used their own modified G722.1 encoding in order to bring this mobile call format up to the level of game audio. vgmstream implemented this special decoding, which would not be correct using the standard G722.1 anyway. Encode/decode game audio files.
4.1 Implementing the same encoding requires powerful algorithms, mathematics, and acoustic capabilities. Specific differences can be seen in the source code of vgmstream.
4.2 Some Japanese friends said that by sending the audio file through a local Japanese phone as a voice text message, you can get a g722.1 format file that can be used in the game.

**Comment by DarkGD123** [comment]
Thanks for the answer and thanks for being active @HaoJun0823 @nachotacos69
