### ISSUE TITLE
missing aragami models

### ISSUE THREAD

**Issue by DarkGD123** [HaoJun0823/GECV#8]
... yeah, some models exists, but i cant find the models of the aragamis

**Comment by nachotacos69** [comment]
🤔

**Comment by nachotacos69** [comment]
sorry for delay respose since im currently doing wacky stuff on vanilla GE2

anyways, this is either you have something went wrong during the process or maybe you got the game somewhere on the internet.

for me i didnt really experienced tons of issues.. but the tool serves more than just somekind of model ripper or something like that, i suggest you should focus to somewhere else

**Comment by DarkGD123** [comment]
thanks again @nachotacos69 for another help from here and through other private messages, i'll keep that in mind
