### ISSUE TITLE
Didnt understand all the tools fuction

### ISSUE THREAD

**Issue by hacxerthanblack** [HaoJun0823/GECV#9]
Can you explain what does each tool do ? 
I know GECV-30_CHS use for Unpack/Repack game files but there are so many options in them that i dont understand , could you eleborate more what each one do?
Thank you

**Comment by HaoJun0823** [comment]
CODE EATER and GOD VEIN were the original packaging/unpacking tools we used for experiments. Since we have complete PRES packaging/unpacking, we abandoned these two tools.
But we still used these two tools when translating GE2RB, so we still kept them.

The detailed structure (currently in Chinese) can be viewed by visiting “噬神者PC版本文件结构1.3.txt”.
GECV_EX_PRES is a replacement for these two tools.

**Comment by HaoJun0823** [comment]
You can use: https://github.com/mhvuze/qpckEater to unpack and package qpck.
You can use Noesis (Written by Rich Whitehouse) to solve GNF problems.
GECV_EX_PRES will automatically decompress/compress blz4 files.
TR2 Editor can edit TR2 files.

**Comment by hacxerthanblack** [comment]
What is the different between pres and blz4 files ?
I use your GECV-30_CHS first option to unpack bin.qpck to a bunch of pres and blz4 files , from then use the second option to and i have these folder 
![image](https://github.com/HaoJun0823/GECV/assets/167430182/468eb9fa-b64c-4962-9f81-7d8c517a9c0d)
As you said above ,should i skip this tool , use qpckEater to unpack qpck to pres and blz4 , then use GECV_EX_PRES
 to decompress them , then edit what i want , right ?

**Comment by HaoJun0823** [comment]
CODE EATER and GOD VEIN are experimental tools I made based on the original reverse engineering:
CODE EATER requires input of two parameters: 1.qpck file, 2. folder.
GOD VEIN only requires 2 folders for packaging.

CODE EATER will generate these directories:
_BASE: Initial QPCK unpacking.
_EXTRA: When GOD VEIN is being packaged, the files inside will overwrite _BASE.

_UNPACK_PRES_REAL:TBD
_UNPACK_QPCK_REAL_EXTRA:TBD

_UNPACK_PRES_REAL_EXTRA_BLZ4:TBD
_UNPACK_RES_REAL_EXTRA:TBD
_UNPACK_RES_REAL_EXTRA_BLZ4:TBD
Brief description: The above files are used for PRES unpacking. Since PRES unpacking will have BLZ4, and QPCK also has BLZ4, it will be unpacked package by package.
The above is no longer supported.

Note: QPCK files are sequential, and hashes cannot be modified. The game will read files according to hash and order. Therefore, there is currently no way to add new files or delete anything to qpck.

The working principle of GOD VEIN is complicated:
It first verifies the original structure and then generates an operation table.
The operation table is an Excel table, which contains the real reference and virtual reference of each PRES, and other columns to determine whether this PRES can be executed by method 1 (replacing files) or method 2 (splicing).
Then, reverse write PRES according to the operation table.

Despite its complexity, this tool can only modify the third set.

So, use GECV_EX_PRES, which completely handles 48 sets per PRES.

**Comment by hacxerthanblack** [comment]
Thanks , How to make GECV_EX_PRES unpack all pres/blz4 files at once ?
I have tried thing like 

> unpack {pres folder] {output folder} 

but it seems like it can only unpack one file at a time ?

**Comment by HaoJun0823** [comment]
> What is the different between pres and blz4 files ? I use your GECV-30_CHS first option to unpack bin.qpck to a bunch of pres and blz4 files , from then use the second option to and i have these folder ![image](https://private-user-images.githubusercontent.com/167430182/324228860-468eb9fa-b64c-4962-9f81-7d8c517a9c0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2ODMyNTgsIm5iZiI6MTcxMzY4Mjk1OCwicGF0aCI6Ii8xNjc0MzAxODIvMzI0MjI4ODYwLTQ2OGViOWZhLWI2NGMtNDk2Mi05ZjgxLTdkOGM1MTdhOWMwZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMVQwNzAyMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OGIxMjk3YWZhMjI3Y2U5MjliMTJmYTAzN2E1ZGY0NTJiOWUwODdjZTM2ZjQwNWQxOTZmMGE0OWUyYjFjYzZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mgCpVOx1TvPsEYU0W2mhrA_BSOFrzsvOeylBZF67Cb4) As you said above ,should i skip this tool , use qpckEater to unpack qpck to pres and blz4 , then use GECV_EX_PRES to decompress them , then edit what i want , right ?

Pres is a complex collection package. The PC version has 1 or 6 areas, and each area has a fixed 8 collections. Therefore, a pres can have up to 48 collections, and there will be other pres in the pres.

Each collection of pres has different storage principles, and the third collection is files.
The third collection will store pres, blz4 and others, the third collection has real and virtual references.
True citation: This file is in this package.
Virtual reference: This file depends on the arrangement of this file by other packages when the game is running.

blz4 is a file compression, and there are scattered blz4 in qpck.
blz4 needs to be decompressed, I will consider making a simpler program to handle this.

**Comment by HaoJun0823** [comment]
> Thanks , How to make GECV_EX_PRES unpack all pres/blz4 files at once ? I have tried thing like
> 
> > unpack {pres folder} {output folder}
> 
> but it seems like it can only unpack one file at a time ?

This can only unzip a pres to a folder, all new tools are single file processing tools.
If you want to batch, you can try to write a cmd script, or other software can achieve it.
Or you can ask GPT to write one for you.

**Comment by nachotacos69** [comment]
i have a little script of mine, but sadly you have to keep pressing any key when "Press Any Key To Exit" shows up
just replace the locations with yours

```
@echo off
REM Batch script to unpack .pres files using GECV_EX_PRES.exe

REM Check if GECV_EX_PRES.exe exists
if not exist "C:\Users\Admin\Documents\GOD EATER PC TOOLS\GECV_EX_PRES7\GECV_EX_PRES.exe" (
    echo Error: GECV_EX_PRES.exe not found.
    exit /b 1
)

REM Unpack method
set method=unpack

REM Folder containing .pres files
set pres_folder=C:\Users\Admin\Documents\GOD EATER PC TOOLS\GECV-30_CHS\bin_qpck_BASE

REM Output folder
set output_folder=extraction

REM Unpack each .pres file in the folder
for %%f in ("%pres_folder%\*.pres") do (
    echo Unpacking %%~nxf...
    "C:\Users\Admin\Documents\GOD EATER PC TOOLS\GECV_EX_PRES7\GECV_EX_PRES.exe" %method% "%%~ff" "%output_folder%"
)

echo Unpacking complete.

**Comment by nachotacos69** [comment]
Thanks @HaoJun0823, im glad that i can help here too even though my knowledge can be a little bit silly

**Comment by hacxerthanblack** [comment]
Thanks so much
